### ISSUE TITLE
job_fragment.yml hardcodes URL

### ISSUE THREAD

**Issue by nathanchance** [nickdesaulniers/github_actions_playground#1]
https://github.com/nickdesaulniers/github_actions_playground/blob/a5cb81a33be488e2e0021a0e39937dcbf76eeb07/job_fragment.yml#L21

This will need to be retrieved from the generator.yml (repo/ref).

**Comment by nickdesaulniers** [comment]
The fragment can be modified via the https://github.com/nickdesaulniers/github_actions_playground/blob/main/generate_workflow.py similar to what is done for the workflow name: https://github.com/nickdesaulniers/github_actions_playground/blob/a5cb81a33be488e2e0021a0e39937dcbf76eeb07/generate_workflow.py#L72

**Comment by nathanchance** [comment]
Whoops, looks like I opened this issue in the wrong repo... Additionally, looks like the branch we worked on early did not get pushed to the CBL org, I think this main branch did.

**Comment by nickdesaulniers** [comment]
> Additionally, looks like the branch we worked on early did not get pushed to the CBL org, I think this main branch did.

Fixed

**Comment by nickdesaulniers** [comment]
looks like I can only transfer issues between my personal repos, not orgs I belong to's repos. Will just refile.
